# Generated by Django 3.1.2 on 2020-10-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
