# Generated by Django 3.1.2 on 2020-11-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201108_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('star', models.FloatField()),
                ('calories', models.IntegerField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
