# Generated by Django 3.1.2 on 2020-12-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
