# Generated by Django 3.1.2 on 2020-12-26 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('WAITING', 'WAITING'), ('CONFIRMED', 'CONFIRMED'), ('IN DELIVERY', 'IN DELIVERY'), ('DELIVERED', 'DELIVERED')], max_length=20)),
                ('total_cost', models.FloatField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.card')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.order')),
            ],
        ),
    ]
