# Generated by Django 3.1.2 on 2020-12-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201226_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='cost',
        ),
    ]
