# Generated by Django 3.1.2 on 2020-12-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_orderdetails_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
