# Generated by Django 3.1.2 on 2021-01-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210123_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
    ]
